# Generated by Django 5.2.15 on 2026-07-05 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('users', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_applications', to='users.user'),
        ),
    ]
