# Generated by Django 5.2.15 on 2026-06-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="security_available",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="listing",
            name="security_details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="security_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("24x7", "24x7 Security"),
                    ("guard", "Security Guard"),
                    ("cctv", "CCTV"),
                    ("gated", "Gated Community"),
                ],
                max_length=20,
            ),
        ),
    ]
