# Generated by Django 5.2.15 on 2026-07-02 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='users.user'),
        ),
        migrations.AddField(
            model_name='listingamenitymapping',
            name='amenity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listingamenity'),
        ),
        migrations.AddField(
            model_name='listingamenitymapping',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenity_mappings', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='listingoffer',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='listingspecification',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='listings.listing'),
        ),
        migrations.AddConstraint(
            model_name='listingamenitymapping',
            constraint=models.UniqueConstraint(fields=('listing', 'amenity'), name='unique_listing_amenity'),
        ),
        migrations.AddConstraint(
            model_name='listingspecification',
            constraint=models.UniqueConstraint(fields=('listing', 'key'), name='unique_listing_spec'),
        ),
    ]
