# Generated by Django 5.2.15 on 2026-07-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='cover_image',
            field=models.URLField(blank=True, help_text='Firebase Storage URL', null=True),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.URLField(help_text='Firebase Storage URL', max_length=500),
        ),
    ]
