# Generated by Django 5.2.15 on 2026-07-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "listings",
            "0002_listing_security_available_listing_security_details_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="district",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
