# Generated by Django 5.2.15 on 2026-07-02 12:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('maps_link', models.URLField(blank=True, help_text='Google Maps URL')),
                ('city', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('service_type', models.CharField(choices=[('restaurant', 'Restaurant'), ('mess', 'Private Mess'), ('taxi', 'Taxi/Auto Service'), ('bus_train', 'Bus & Train'), ('hospital', 'Hospital'), ('medical_shop', 'Medical Shop'), ('supermarket', 'Supermarket'), ('atm_banking', 'ATM & Banking'), ('attraction', 'Attraction'), ('security', 'Security & Police'), ('ambulance', 'Ambulance'), ('education', 'Education Institute'), ('other', 'Other')], default='other', max_length=20)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_type', models.CharField(choices=[('police', 'Police Station'), ('pink_police', 'Pink Police'), ('fire', 'Fire Station')], max_length=20)),
                ('emergency_number', models.CharField(blank=True, max_length=30)),
                ('is_24_7', models.BooleanField(default=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_detail', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='MessRestaurantDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(choices=[('veg', 'Vegetarian'), ('non_veg', 'Non-Vegetarian'), ('both', 'Both')], default='both', max_length=10)),
                ('meal_times', models.CharField(blank=True, help_text='e.g. Breakfast 7-10am, Lunch 12-3pm, Dinner 7-10pm', max_length=200)),
                ('is_mess', models.BooleanField(default=False)),
                ('monthly_plan_available', models.BooleanField(default=False)),
                ('monthly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('menu_image', models.ImageField(blank=True, null=True, upload_to='services/menus/')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mess_detail', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_emergency', models.BooleanField(default=False)),
                ('is_24_7', models.BooleanField(default=False)),
                ('ambulance_number', models.CharField(blank=True, max_length=30)),
                ('specializations', models.CharField(blank=True, help_text='e.g. Cardiology, Orthopaedics', max_length=255)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_detail', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='EducationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_type', models.CharField(choices=[('school', 'School'), ('college', 'College'), ('university', 'University'), ('coaching', 'Coaching Center'), ('other', 'Other')], max_length=20)),
                ('courses_offered', models.CharField(blank=True, help_text='e.g. Engineering, Medical, Arts', max_length=255)),
                ('is_government', models.BooleanField(default=False)),
                ('established_year', models.PositiveIntegerField(blank=True, null=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='education_detail', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='AttractionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attraction_type', models.CharField(choices=[('theatre', 'Film Theatre'), ('railway_station', 'Railway Station'), ('mall', 'Mall'), ('park', 'Park'), ('museum', 'Museum'), ('temple', 'Temple/Religious Site'), ('other', 'Other')], max_length=20)),
                ('entry_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank if free entry', max_digits=8, null=True)),
                ('is_free', models.BooleanField(default=False)),
                ('opening_hours', models.CharField(blank=True, help_text='e.g. 9am – 9pm', max_length=100)),
                ('is_24_7', models.BooleanField(default=False)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attraction_detail', to='services.service')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.servicecategory'),
        ),
        migrations.CreateModel(
            name='TransportDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(choices=[('taxi', 'Taxi'), ('auto', 'Auto Rickshaw'), ('bike', 'Bike Taxi')], max_length=10)),
                ('base_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('per_km_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_24_7', models.BooleanField(default=False)),
                ('availability_hours', models.CharField(blank=True, max_length=100)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transport_detail', to='services.service')),
            ],
        ),
    ]
