# Generated by Django 5.2.15 on 2026-07-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, help_text="Short note Maps won't tell you, e.g. '24/7 govt hospital, 2km from campus'"),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.URLField(blank=True, help_text='Firebase Storage URL'),
        ),
        migrations.AlterField(
            model_name='messrestaurantdetail',
            name='menu_image',
            field=models.URLField(blank=True, help_text='Firebase Storage URL — menu photo'),
        ),
    ]
