# Generated by Django 5.2.15 on 2026-06-29 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="address",
        ),
        migrations.RemoveField(
            model_name="service",
            name="country",
        ),
        migrations.RemoveField(
            model_name="service",
            name="description",
        ),
        migrations.RemoveField(
            model_name="service",
            name="email",
        ),
        migrations.RemoveField(
            model_name="service",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="service",
            name="listings",
        ),
        migrations.RemoveField(
            model_name="service",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="service",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="service",
            name="website",
        ),
        migrations.RemoveField(
            model_name="servicecategory",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="servicecategory",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="service",
            name="maps_link",
            field=models.URLField(blank=True, help_text="Google Maps URL"),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("restaurant", "Restaurant"),
                    ("mess", "Private Mess"),
                    ("taxi", "Taxi/Auto Service"),
                    ("bus_train", "Bus & Train"),
                    ("hospital", "Hospital"),
                    ("medical_shop", "Medical Shop"),
                    ("supermarket", "Supermarket"),
                    ("atm_banking", "ATM & Banking"),
                    ("attraction", "Attraction"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AttractionDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attraction_type",
                    models.CharField(
                        choices=[
                            ("theatre", "Film Theatre"),
                            ("railway_station", "Railway Station"),
                            ("mall", "Mall"),
                            ("park", "Park"),
                            ("museum", "Museum"),
                            ("temple", "Temple/Religious Site"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "entry_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Leave blank if free entry",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("is_free", models.BooleanField(default=False)),
                (
                    "opening_hours",
                    models.CharField(
                        blank=True, help_text="e.g. 9am – 9pm", max_length=100
                    ),
                ),
                ("is_24_7", models.BooleanField(default=False)),
                (
                    "service",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attraction_detail",
                        to="services.service",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HospitalDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("has_emergency", models.BooleanField(default=False)),
                ("is_24_7", models.BooleanField(default=False)),
                ("ambulance_number", models.CharField(blank=True, max_length=30)),
                (
                    "specializations",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Cardiology, Orthopaedics",
                        max_length=255,
                    ),
                ),
                (
                    "service",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospital_detail",
                        to="services.service",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MessRestaurantDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "food_type",
                    models.CharField(
                        choices=[
                            ("veg", "Vegetarian"),
                            ("non_veg", "Non-Vegetarian"),
                            ("both", "Both"),
                        ],
                        default="both",
                        max_length=10,
                    ),
                ),
                (
                    "meal_times",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Breakfast 7-10am, Lunch 12-3pm, Dinner 7-10pm",
                        max_length=200,
                    ),
                ),
                ("is_mess", models.BooleanField(default=False)),
                ("monthly_plan_available", models.BooleanField(default=False)),
                (
                    "monthly_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "menu_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="services/menus/"
                    ),
                ),
                (
                    "service",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mess_detail",
                        to="services.service",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransportDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transport_type",
                    models.CharField(
                        choices=[
                            ("taxi", "Taxi"),
                            ("auto", "Auto Rickshaw"),
                            ("bike", "Bike Taxi"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "base_fare",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "per_km_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("is_24_7", models.BooleanField(default=False)),
                ("availability_hours", models.CharField(blank=True, max_length=100)),
                (
                    "service",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_detail",
                        to="services.service",
                    ),
                ),
            ],
        ),
    ]
