# Generated by Django 5.2.15 on 2026-06-30 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_remove_service_address_remove_service_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicecategory",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("restaurant", "Restaurant"),
                    ("mess", "Private Mess"),
                    ("taxi", "Taxi/Auto Service"),
                    ("bus_train", "Bus & Train"),
                    ("hospital", "Hospital"),
                    ("medical_shop", "Medical Shop"),
                    ("supermarket", "Supermarket"),
                    ("atm_banking", "ATM & Banking"),
                    ("attraction", "Attraction"),
                    ("security", "Security & Police"),
                    ("ambulance", "Ambulance"),
                    ("education", "Education Institute"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="EducationDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "institute_type",
                    models.CharField(
                        choices=[
                            ("school", "School"),
                            ("college", "College"),
                            ("university", "University"),
                            ("coaching", "Coaching Center"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "courses_offered",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Engineering, Medical, Arts",
                        max_length=255,
                    ),
                ),
                ("is_government", models.BooleanField(default=False)),
                (
                    "established_year",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "service",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education_detail",
                        to="services.service",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SecurityDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "security_type",
                    models.CharField(
                        choices=[
                            ("police", "Police Station"),
                            ("pink_police", "Pink Police"),
                            ("fire", "Fire Station"),
                        ],
                        max_length=20,
                    ),
                ),
                ("emergency_number", models.CharField(blank=True, max_length=30)),
                ("is_24_7", models.BooleanField(default=True)),
                (
                    "service",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_detail",
                        to="services.service",
                    ),
                ),
            ],
        ),
    ]
