# Generated by Django 5.2.15 on 2026-06-29 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_essentialcategory_essential_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="essential",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="essentials",
                to="categories.essentialcategory",
            ),
        ),
    ]
