# Generated by Django 5.2.15 on 2026-06-30 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0003_alter_essential_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="essential",
            name="category",
        ),
        migrations.RemoveField(
            model_name="essential",
            name="seller",
        ),
        migrations.DeleteModel(
            name="EssentialCategory",
        ),
        migrations.DeleteModel(
            name="Essential",
        ),
    ]
