# Generated by Django 5.2.15 on 2026-07-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_remove_essential_category_remove_essential_seller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='image',
            field=models.URLField(blank=True, help_text='Firebase Storage URL'),
        ),
        migrations.AlterField(
            model_name='housingcategory',
            name='image',
            field=models.URLField(blank=True, help_text='Firebase Storage URL'),
        ),
    ]
