# Generated by Django 5.2.15 on 2026-07-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_alter_expensecategory_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='image',
            field=models.URLField(blank=True, help_text='Firebase Storage URL', null=True),
        ),
    ]
