# Generated by Django 5.2.15 on 2026-07-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_alter_expensecategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='image',
            field=models.URLField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='housingcategory',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
