# Generated by Django 5.2.15 on 2026-06-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emergency", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emergencycontact",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="emergencycontact",
            name="longitude",
        ),
        migrations.AddField(
            model_name="emergencycontact",
            name="maps_link",
            field=models.URLField(blank=True, help_text="Google Maps URL"),
        ),
        migrations.AlterField(
            model_name="emergencycontact",
            name="contact_type",
            field=models.CharField(
                choices=[
                    ("police", "Police"),
                    ("pink_police", "Pink Police"),
                    ("hospital", "Hospital"),
                    ("fire", "Fire Station"),
                    ("embassy", "Embassy"),
                    ("ambulance", "Ambulance"),
                    ("pharmacy", "Pharmacy"),
                    ("drug_helpline", "Drug Helpline"),
                ],
                max_length=20,
            ),
        ),
    ]
