# Generated by Django 5.2.15 on 2026-07-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityclimate',
            name='banner_image',
            field=models.URLField(blank=True, help_text='Firebase Storage URL', null=True),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='image',
            field=models.URLField(blank=True, help_text='Firebase Storage URL', null=True),
        ),
    ]
